apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: shopnow
spec:
  replicas: {{ .Values.frontend.replicacount }}
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend-deployment
          image: "{{ .Values.ecr_repo_frontend }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: shopnow-configmap
                  key: MONGODB_URI
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopnow
spec:
  selector:
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

